name: macOS 10.15

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'glib glib-networking gobject-introspection pkg-config jq' }}

on:
  push:
    branches:
      - swift52
  pull_request:
    branches:
      - swift52

jobs:
  # macOS tasks
  build-mac-catalina-swift-latest:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout SwiftGIO
        uses: actions/checkout@v2
        with:
          ref: swift52
          path: SwiftGIO

      - name: Build Swift Wrappers
        run: |
          cd SwiftGIO
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftGIO
        run: |
          cd SwiftGIO
          swift build `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Test SwiftGIO
        run: |
          cd SwiftGIO
          swift test `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd SwiftGIO
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-macos
          path: |
            SwiftGIO/Sources/
          retention-days: 1
