name: Linux

# Dependencies of this package
env:
  UBUNTU_APT: ${{ 'libglib2.0-dev glib-networking gobject-introspection libgirepository1.0-dev libxml2-dev jq' }}

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  build-linux:
    strategy: 
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
        swift: ['5.9', '5.7']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Print Linux and Swift version
        run: |
          lsb_release -d
          swift --version

      - name: Fetch Linux dependencies
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout SwiftGIO
        uses: actions/checkout@v4
        with:
          path: SwiftGIO

      - name: Build SwiftGIO
        run: |
          cd SwiftGIO
          swift build
          cd ..

      - name: Test SwiftGIO
        run: |
          cd SwiftGIO
          swift test
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: | 
          cd SwiftGIO
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artefact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artefact-${{ matrix.os }}-${{ matrix.swift }}
          path: |
            SwiftGIO/Sources/
          retention-days: 1
