name: macOS 12

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'glib glib-networking gobject-introspection pkg-config jq' }}

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  # macOS tasks
  build-mac-monterey-latest:
    runs-on: macos-12.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.3.1'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout SwiftGIO
        uses: actions/checkout@v2
        with:
          path: SwiftGIO

      - name: Build SwiftGIO
        run: |
          cd SwiftGIO
          swift build
          cd ..

      - name: Test SwiftGIO
        run: |
          cd SwiftGIO
          swift test
          cd ..

      - name: Remove unneeded files and archive artefacts
        run: | 
          cd SwiftGIO
          swift package clean
          rm -rf .build/repositories
          cd ..
